# Generated by Django 4.1.1 on 2022-09-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article',
            new_name='type',
        ),
    ]
